### ISSUE TITLE
Can't set config option localeResolvers

### ISSUE THREAD

**Issue by foxycode** [contributte/translation#7]
When I set `localeResolvers` option in `config.neon`, I see this error:

```php
Service 'translation.localeResolverRouter' has already been added.
```

My full config:
```yaml
extensions:
    translation: Contributte\Translation\DI\TranslationExtension

translation:
    locales:
        whitelist: [cs, en]
        default: cs
        fallback: [en]
    dirs:
        - %appDir%/Lang
    localeResolvers:
        - Contributte\Translation\LocalesResolvers\Router
        - Contributte\Translation\LocalesResolvers\Parameter
```
